language: python

python:
  - "3.7"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py db init
  - python manage.py migrate
  - python manage.py db upgrade

script:
  - pytest tests

after_success:
  - codecov