language: python

python:
  - "3.7"

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov

# before_script:
#   - python app/manage.py db init
#   - python app/manage.py migrate
#   - python app/manage.py db upgrade

script:
  - pytest --cov=app tests

after_success:
  - codecov